config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#root'

  resource :session, only: [:create, :new, :destroy]
  resources :users, only: [:new, :create]

  namespace :api, defaults: {format: :json} do
    resources :users, only: [:show] do
      resources :groups, only: [:index]
      resources :posts, only: [:index]
    end
    resources :posts
    resources :groups
    resources :group_memberships
    resources :link_memberships
    resources :tags
    resources :likes
    resources :comments
    resources :group_messages
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :text, :user, :post, null: false
  belongs_to :user
  belongs_to :post

end

app/models/group.rb
class Group < ActiveRecord::Base
  validates :title, presence: true

  has_many(
  :memberships,
  class_name: :GroupMembership,
  foreign_key: :group_id,
  primary_key: :id,
  dependent: :destroy
  )

  has_many(
  :link_memberships,
  class_name: :LinkMembership,
  foreign_key: :group_id,
  primary_key: :id,
  dependent: :destroy
  )



  has_many :members, through: :memberships, source: :member
  has_many :posts, through: :link_memberships, source: :post
  has_many :group_messages
end

app/models/group_membership.rb
class GroupMembership < ActiveRecord::Base
  validates :group_id, :user_id, presence: true
  validates :group_id, uniqueness: {scope: :user_id}

  belongs_to(
  :member,
  class_name: :User,
  foreign_key: :user_id,
  primary_key: :id
  )

  belongs_to(
  :group,
  class_name: :Group,
  foreign_key: :group_id,
  primary_key: :id
  )
end

app/models/group_message.rb
class GroupMessage < ActiveRecord::Base
  belongs_to :group
  belongs_to :user
end

app/models/like.rb
class Like < ActiveRecord::Base
  validates :post_id, :user_id, presence: true
  validates :post, uniqueness: {scope: :user_id}

  belongs_to :user
  belongs_to :post
end

app/models/link_membership.rb
class LinkMembership < ActiveRecord::Base
  validates :post, :group_id, presence: true
  validates :group, uniqueness: {scope: :post_id}

  belongs_to :group
  belongs_to :post
end

app/models/post.rb
require 'set'
class Post < ActiveRecord::Base
  after_save :send_notification_email

  validates :user_id, :title, :url, :group_ids, :tag_ids, presence: true


  belongs_to :user

  has_many :link_memberships,
  dependent: :destroy
  # has_many(:link_memberships,
  # class_name: :LinkMembership,
  # foreign_key: :post_id,
  # primary_key: :id,
  # inverse_of: :post
  # )
  has_many :taggings,
  dependent: :destroy
  has_many :tags, through: :taggings, source: :tag
  has_many :likes,
  dependent: :destroy
  has_many :likers, through: :likes, source: :user
  has_many :comments
  has_many :groups, through: :link_memberships, source: :group

  def send_notification_email
    poster = self.user
    groups = self.groups
    mailed_to_members = Set.new
    groups.each do |group|
      group.members.each do |member|
      next if member.id == poster.id
        if !mailed_to_members.include?(member)
          mailed_to_members << member
          UserMailer.new_post_mail(member, poster, self).deliver_now
        end
      end
    end
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  validates_inclusion_of :name, in: ['Media', 'News', 'Restaurants', 'Useful Stuff', 'Business', "Op-Eds", 'Random', "Sports", 'Fashion', 'Tech']
  validates :name, uniqueness: true, presence: true

  has_many :taggings
  has_many :posts, through: :taggings, source: :post

end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  validates :post, :tag_id, presence: true
  validates :post, uniqueness: {scope: :tag_id}

  belongs_to :tag
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  after_initialize :ensure_session_token
  attr_reader :password
  validates :password, length: {minimum: 6, allow_nil: true}
  validates :fname, :lname, :email, :password_digest, :session_token, presence: true
  validates :email, :session_token, uniqueness: true

  has_many(
  :memberships,
  class_name: :GroupMembership,
  foreign_key: :user_id,
  primary_key: :id,
  dependent: :destroy
  )

  has_many :posts

  has_many :likes,
  dependent: :destroy

  has_many :comments
  has_many :group_messages

  has_many :liked_posts, through: :likes, source: :post


  has_many :groups, through: :memberships, source: :group

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil if user.nil?
    user.valid_password?(password) ? user : nil
  end

  def valid_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token
    self.session_token = SecureRandom::urlsafe_base64
    self.save!
    self.session_token
  end

  def is_member_of?(group)
    member = group.memberships.where(user_id: self.id)
    member.empty? ? false : true
  end

  def is_first_member_of?(group)
    member_id = group.memberships.first.user_id
    member_id == self.id ? member_id : nil
  end

  def likes?(post)
    like = post.likes.where(user_id: self.id)
    like.empty? ? false : true
  end

  protected
  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end

end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    render :show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_credentials(params[:user][:email],
    params[:user][:password])

    if user
        if user.email === 'guest1@gmail.com'
          generate_user_data(user)
          sign_in!(user)
        else
          sign_in!(user)
        end
      redirect_to root_url
    else
      flash.now[:errors] = ["Invalid Email or Password"]
      render :new
    end
  end

  def new
    render :new
  end

  def destroy
    sign_out!
  render :new
  end

  def generate_user_data(user)
    Post.delete_all("user_id=2")
    Comment.delete_all("user_id=2")
    GroupMessage.delete_all("user_id=2")
    user.memberships.delete_all
    GroupMembership.create!({user_id: user.id, group_id: 1})
    GroupMembership.create!({user_id: user.id, group_id: 2})
    GroupMembership.create!({user_id: user.id, group_id: 3})
    Post.create!(title: "Why China's economy is slowing", url: "http://www.economist.com/blogs/economist-explains/2015/03/economist-explains-8", description: "", user_id: user.id, group_ids: [2], tag_ids: [1,4])
    Comment.create!({text: "This is awesome", post_id: 22, user_id: 2},)

  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    def index
      @tags = Tag.all
      render json: @tags
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :redirect_if_logged_in

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in!(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def new
    sign_out! if current_user
    @user = User.new
    render :new
  end

  private
  def user_params
    params.require(:user).permit(:fname, :lname, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/group_messages_helper.rb
module GroupMessagesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/link_memberships_helper.rb
module LinkMembershipsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<!-- <div class="container">


<%if !current_user%>
<h1>Sign Up</h1>

<form action="/users" method="post">

  <label>First Name</label>
  <input type="text" name="user[fname]" value="<%=@user.fname%>"> <br>
  <label >Last Name</label>
  <input type="text" name="user[lname]" value="<%=@user.lname%>"> <br>

  <label>Email Address</label>
  <input type="text" name="user[email]" value="<%=@user.email%>"> <br>
  <label >Password</label>
  <input type="password" name="user[password]">  <br>

  <input type="submit" name="Submit" class="btn btn-primary">

</form>
<%end%>
</div> -->



<%if !current_user%>
<div class="container">
  <header>
    <h1 id="logo">Cliquely.io</h1>
    <h4 id="mvp">Share, sort, and save your favorite content on the web</h4>
  </header>
  <div class="group"></div>
  <div id="top-bar"></div>

    <!-- <div class="landing"> -->
      <div id="wrap" class="group">

    <div class="group" id="sign-up">

      <h1 class="log-in-title">Sign Up</h1>
      <form action="<%=users_url%>" method="post">
      <h4>First Name</h4>
      <input type="text" name="user[fname]" value="<%=@user.fname%>">
      <h4>Last Name</h4>
      <input type="text" name="user[lname]" value="<%=@user.lname%>">
      <h4>Email Address</h4>
      <div class=form-group>
        <input type="text" name="user[email]" value="<%=@user.email%>">
      </div>
      <h4 >Password</h4>
      <div class=form-group>
        <input id="password" type="password" name="user[password]" value="">
      </div>
    <div >
      <input id="submit" class="sign-up-btn btn btn-primary" type="submit" name="Submit" class="btn btn-primary">
    </div>
    </form>
    <span class="sign-in-link"><%=link_to "Already Signed Up? Sign In Here", new_session_url%></span>
  </div>
  </div>

  <div class="errors">
    <% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
    <span><%=error%><br></span>
    <%end%>
    <%end%>
  </div>
  <!-- </div> -->
</div>
    <footer class="footer">
       <div class="container">
           <div class=" row">
               <div class="col-lg-12">
                   <ul class="list-inline">
                       <li>
                           <a href="#">Home</a>
                       </li>
                       <li class="footer-menu-divider">&sdot;</li>
                       <li>
                           <a href="https://www.linkedin.com/in/gauravnagpal19">About</a>
                       </li>
                       <li class="footer-menu-divider">&sdot;</li>
                       <li>
                           <a href="mailto:gauravnagpal19@gmail.com">Contact</a>
                       </li>
                   </ul>
                   <p class="copyright text-muted small">Copyright &copy; Cliquely 2015. All Rights Reserved</p>
               </div>
           </div>
       </div>
    </footer>
    <% else%>
    <h1>Sign Out</h1>
    <%=button_to "Sign Out", session_url, method: :delete%>
  </div>
  </div>
  <!-- </div> -->
</div>



    <%end%>