config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#root'

  resource :session, only: [:create, :new, :destroy]
  resources :users, only: [:new, :create]

  namespace :api, defaults: {format: :json} do
    resources :users, only: [:show] do
      resources :groups, only: [:index]
      resources :posts, only: [:index]
    end
    resources :posts
    resources :groups
    resources :group_memberships
    resources :link_memberships
    resources :tags
    resources :likes
    resources :comments
    resources :group_messages
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :text, :user, :post, null: false
  belongs_to :user
  belongs_to :post

end

app/models/group.rb
class Group < ActiveRecord::Base
  validates :title, presence: true

  has_many(
  :memberships,
  class_name: :GroupMembership,
  foreign_key: :group_id,
  primary_key: :id,
  dependent: :destroy
  )

  has_many(
  :link_memberships,
  class_name: :LinkMembership,
  foreign_key: :group_id,
  primary_key: :id,
  dependent: :destroy
  )



  has_many :members, through: :memberships, source: :member
  has_many :posts, through: :link_memberships, source: :post
  has_many :group_messages
end

app/models/group_membership.rb
class GroupMembership < ActiveRecord::Base
  validates :group_id, :user_id, presence: true
  validates :group_id, uniqueness: {scope: :user_id}

  belongs_to(
  :member,
  class_name: :User,
  foreign_key: :user_id,
  primary_key: :id
  )

  belongs_to(
  :group,
  class_name: :Group,
  foreign_key: :group_id,
  primary_key: :id
  )
end

app/models/group_message.rb
class GroupMessage < ActiveRecord::Base
  belongs_to :group
  belongs_to :user
end

app/models/like.rb
class Like < ActiveRecord::Base
  validates :post_id, :user_id, presence: true
  validates :post, uniqueness: {scope: :user_id}

  belongs_to :user
  belongs_to :post
end

app/models/link_membership.rb
class LinkMembership < ActiveRecord::Base
  validates :post, :group_id, presence: true
  validates :group, uniqueness: {scope: :post_id}

  belongs_to :group
  belongs_to :post
end

app/models/post.rb
require 'set'
class Post < ActiveRecord::Base
  after_save :send_notification_email

  validates :user_id, :title, :url, :group_ids, :tag_ids, presence: true


  belongs_to :user

  has_many :link_memberships,
  dependent: :destroy
  # has_many(:link_memberships,
  # class_name: :LinkMembership,
  # foreign_key: :post_id,
  # primary_key: :id,
  # inverse_of: :post
  # )
  has_many :taggings,
  dependent: :destroy
  has_many :tags, through: :taggings, source: :tag
  has_many :likes,
  dependent: :destroy
  has_many :likers, through: :likes, source: :user
  has_many :comments
  has_many :groups, through: :link_memberships, source: :group

  def send_notification_email
    poster = self.user
    groups = self.groups
    mailed_to_members = Set.new
    groups.each do |group|
      group.members.each do |member|
      next if member.id == poster.id
        if !mailed_to_members.include?(member)
          mailed_to_members << member
          UserMailer.new_post_mail(member, poster, self).deliver_now
        end
      end
    end
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  validates_inclusion_of :name, in: ['Media', 'News', 'Restaurants', 'Useful Stuff', 'Business', "Op-Eds", 'Random', "Sports", 'Fashion', 'Tech']
  validates :name, uniqueness: true, presence: true

  has_many :taggings
  has_many :posts, through: :taggings, source: :post

end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  validates :post, :tag_id, presence: true
  validates :post, uniqueness: {scope: :tag_id}

  belongs_to :tag
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  after_initialize :ensure_session_token
  attr_reader :password
  validates :password, length: {minimum: 6, allow_nil: true}
  validates :fname, :lname, :email, :password_digest, :session_token, presence: true
  validates :email, :session_token, uniqueness: true

  has_many(
  :memberships,
  class_name: :GroupMembership,
  foreign_key: :user_id,
  primary_key: :id,
  dependent: :destroy
  )

  has_many :posts

  has_many :likes,
  dependent: :destroy

  has_many :comments
  has_many :group_messages

  has_many :liked_posts, through: :likes, source: :post


  has_many :groups, through: :memberships, source: :group

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil if user.nil?
    user.valid_password?(password) ? user : nil
  end

  def valid_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token
    self.session_token = SecureRandom::urlsafe_base64
    self.save!
    self.session_token
  end

  def is_member_of?(group)
    member = group.memberships.where(user_id: self.id)
    member.empty? ? false : true
  end

  def is_first_member_of?(group)
    member_id = group.memberships.first.user_id
    member_id == self.id ? member_id : nil
  end

  def likes?(post)
    like = post.likes.where(user_id: self.id)
    like.empty? ? false : true
  end

  protected
  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    def index
      @tags = Tag.all
      render json: @tags
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :redirect_if_logged_in

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in!(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def new
    sign_out! if current_user
    @user = User.new
    render :new
  end

  private
  def user_params
    params.require(:user).permit(:fname, :lname, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">OurLinks</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     <ul class="nav navbar-nav navbar-right">
       <% if current_user %>
       <!-- <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li> -->
       <!-- <li><a href="#">Link</a></li> -->
       <li><a class="new-post" href="#">New Post</a></li>
       <li class="dropdown">
         <a href="#" class="dropdown-toggle btn btn-default" data-toggle="dropdown" role="button" aria-expanded="false"><%=current_user.fname%> <span class="caret"></span></a>
         <ul class="dropdown-menu" role="menu">
           <li><a href="#/users/<%=current_user.id%>">Profile</a></li>
           <li><a class="new-post" href="#">New Post</a></li>
           <li><a href="#/groups">All Groups</a></li>
           <li class="divider"></li>
           <li><a href="#">Separated link</a></li>
           <li class="divider"></li>
           <li><a href="#">One more separated link</a></li>
         </ul>
       </li>
       <li><%= button_to "Sign out", session_url, method: :delete, class: "btn btn-default" %></li>
       <% else %>
         <li><%= link_to "Log in", new_session_url %></li>
         <li><%= link_to "Sign up", new_user_url %></li>
       <% end %>
     </ul>
     <% if current_user %>
     <form class="navbar-form navbar-right" role="search">
       <div class="form-group">
         <input type="text" class="form-control" placeholder="Search">
       </div>
       <button type="submit" class="btn btn-default">Submit</button>
     </form>
     <% end %>
   </div>
 </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>cliquely.io</title>
  <link href='http://fonts.googleapis.com/css?family=Oxygen:400,700' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Marck+Script|Grand+Hotel|Merienda+One|Satisfy|Merienda:400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <link rel="stylesheet" href="shepherd-theme-arrows.css" />
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

<body>


<%= yield %>


</body>

<% if current_user %>
<script>OurLinks.currentUserId = <%= current_user.id %></script>
<%end%>
</html>